/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    noticias: Noticia;
    paginas: Pagina;
    categorias: Categoria;
    etiquetas: Etiqueta;
    menus: Menu;
    medios: Medio;
    documentos: Documento;
    usuarios: Usuario;
    bitacora: Bitacora;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    etiquetas: EtiquetasSelect<false> | EtiquetasSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    bitacora: BitacoraSelect<false> | BitacoraSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * El editor guarda borradores y los marca como listos; el publicador los aprueba y publica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  fecha: string;
  lugar: string;
  imagen: number | Medio;
  resumen: string;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Si el contenido proviene de una fuente externa, indíquela con su enlace directo.
   */
  fuente?: {
    nombre?: string | null;
    url?: string | null;
  };
  categorias?: (number | Categoria)[] | null;
  etiquetas?: (number | Etiqueta)[] | null;
  /**
   * El editor la marca cuando el borrador está listo para publicar.
   */
  listaParaRevision?: boolean | null;
  seo?: {
    /**
     * Si se deja vacío se usa el título. Máximo 70 caracteres.
     */
    titulo?: string | null;
    /**
     * Resumen propio de esta página. Máximo 160 caracteres.
     */
    descripcion?: string | null;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  /**
   * Describa lo que muestra la imagen para quien no puede verla (A2 7.01.a).
   */
  alt: string;
  credito?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tarjeta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    completa?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas".
 */
export interface Etiqueta {
  id: number;
  nombre: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titulo: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  /**
   * Por ejemplo, «Historia» va dentro de «Sobre nosotros».
   */
  padre?: (number | null) | Pagina;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  listaParaRevision?: boolean | null;
  seo?: {
    /**
     * Si se deja vacío se usa el título. Máximo 70 caracteres.
     */
    titulo?: string | null;
    /**
     * Resumen propio de esta página. Máximo 160 caracteres.
     */
    descripcion?: string | null;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  nombre: string;
  ubicacion: 'principal' | 'pie-informate';
  elementos?:
    | {
        etiqueta: string;
        /**
         * Interna (/sobre-nosotros/historia) o externa (https://...). Las externas abren en pestaña nueva.
         */
        url: string;
        hijos?:
          | {
              etiqueta: string;
              /**
               * Interna (/sobre-nosotros/historia) o externa (https://...). Las externas abren en pestaña nueva.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  titulo: string;
  /**
   * Qué contiene el documento, en lenguaje simple.
   */
  descripcion: string;
  fechaCreacion: string;
  area: 'institucional' | 'transparencia';
  categoria?: (number | null) | Categoria;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Las cuentas y los roles se administran en Entra ID. Aquí solo se activa o desactiva el acceso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  email: string;
  /**
   * Asignados en Entra ID (roles de aplicación).
   */
  roles?: ('editor' | 'publicador' | 'oai' | 'administrador' | 'auditor')[] | null;
  activo?: boolean | null;
  entraOid?: string | null;
  ultimoAcceso?: string | null;
  sesionId?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'usuarios';
}
/**
 * Registro inalterable de accesos, permisos y publicaciones. Solo lectura.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora".
 */
export interface Bitacora {
  id: number;
  fecha: string;
  evento:
    | 'inicio_sesion'
    | 'inicio_sesion_rechazado'
    | 'cierre_sesion'
    | 'creacion'
    | 'modificacion'
    | 'publicacion'
    | 'despublicacion'
    | 'eliminacion'
    | 'cambio_permisos';
  usuarioId?: string | null;
  usuarioCorreo?: string | null;
  coleccion?: string | null;
  documentoId?: string | null;
  titulo?: string | null;
  ip?: string | null;
  detalle?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'etiquetas';
        value: number | Etiqueta;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'bitacora';
        value: number | Bitacora;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  fecha?: T;
  lugar?: T;
  imagen?: T;
  resumen?: T;
  contenido?: T;
  fuente?:
    | T
    | {
        nombre?: T;
        url?: T;
      };
  categorias?: T;
  etiquetas?: T;
  listaParaRevision?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  padre?: T;
  contenido?: T;
  listaParaRevision?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas_select".
 */
export interface EtiquetasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  nombre?: T;
  ubicacion?: T;
  elementos?:
    | T
    | {
        etiqueta?: T;
        url?: T;
        hijos?:
          | T
          | {
              etiqueta?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tarjeta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        completa?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  fechaCreacion?: T;
  area?: T;
  categoria?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  roles?: T;
  activo?: T;
  entraOid?: T;
  ultimoAcceso?: T;
  sesionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora_select".
 */
export interface BitacoraSelect<T extends boolean = true> {
  fecha?: T;
  evento?: T;
  usuarioId?: T;
  usuarioCorreo?: T;
  coleccion?: T;
  documentoId?: T;
  titulo?: T;
  ip?: T;
  detalle?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}