/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    noticias: Noticia;
    paginas: Pagina;
    servicios: Servicio;
    diapositivas: Diapositiva;
    banners: Banner;
    'preguntas-frecuentes': PreguntasFrecuente;
    categorias: Categoria;
    etiquetas: Etiqueta;
    menus: Menu;
    medios: Medio;
    documentos: Documento;
    'textos-transparencia': TextosTransparencia;
    casos: Caso;
    encuestas: Encuesta;
    usuarios: Usuario;
    bitacora: Bitacora;
    redirecciones: Redireccione;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    servicios: ServiciosSelect<false> | ServiciosSelect<true>;
    diapositivas: DiapositivasSelect<false> | DiapositivasSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'preguntas-frecuentes': PreguntasFrecuentesSelect<false> | PreguntasFrecuentesSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    etiquetas: EtiquetasSelect<false> | EtiquetasSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    'textos-transparencia': TextosTransparenciaSelect<false> | TextosTransparenciaSelect<true>;
    casos: CasosSelect<false> | CasosSelect<true>;
    encuestas: EncuestasSelect<false> | EncuestasSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    bitacora: BitacoraSelect<false> | BitacoraSelect<true>;
    redirecciones: RedireccionesSelect<false> | RedireccionesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    institucion: Institucion;
    portada: Portada;
  };
  globalsSelect: {
    institucion: InstitucionSelect<false> | InstitucionSelect<true>;
    portada: PortadaSelect<false> | PortadaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * El editor guarda borradores y los marca como listos; el publicador los aprueba y publica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  fecha: string;
  lugar: string;
  imagen: number | Medio;
  resumen: string;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Si el contenido proviene de una fuente externa, indíquela con su enlace directo.
   */
  fuente?: {
    nombre?: string | null;
    url?: string | null;
  };
  categorias?: (number | Categoria)[] | null;
  etiquetas?: (number | Etiqueta)[] | null;
  /**
   * El editor la marca cuando el borrador está listo para publicar.
   */
  listaParaRevision?: boolean | null;
  seo?: {
    /**
     * Si se deja vacío se usa el título. Máximo 70 caracteres.
     */
    titulo?: string | null;
    /**
     * Resumen propio de esta página. Máximo 160 caracteres.
     */
    descripcion?: string | null;
    noIndexar?: boolean | null;
  };
  origen?: {
    url?: string | null;
    identificador?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  /**
   * Describa lo que muestra la imagen para quien no puede verla (A2 7.01.a). Si la imagen tiene texto, inclúyalo.
   */
  alt: string;
  credito?: string | null;
  origen?: {
    url?: string | null;
    identificador?: string | null;
  };
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tarjeta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    completa?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas".
 */
export interface Etiqueta {
  id: number;
  nombre: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  titulo: string;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  /**
   * Por ejemplo, «Historia» va dentro de «Sobre nosotros».
   */
  padre?: (number | null) | Pagina;
  /**
   * Por ejemplo, la foto de las instalaciones (Quiénes somos) o del Gerente General.
   */
  imagen?: (number | null) | Medio;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Se muestran al final con descripción, tamaño, fecha y tipo (p. ej., el organigrama).
   */
  documentos?: (number | Documento)[] | null;
  listaParaRevision?: boolean | null;
  seo?: {
    /**
     * Si se deja vacío se usa el título. Máximo 70 caracteres.
     */
    titulo?: string | null;
    /**
     * Resumen propio de esta página. Máximo 160 caracteres.
     */
    descripcion?: string | null;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  titulo: string;
  /**
   * Qué contiene el documento, en lenguaje simple.
   */
  descripcion: string;
  fechaCreacion: string;
  area: 'institucional' | 'transparencia';
  seccion?: ('general' | 'marco-legal' | 'organigrama') | null;
  /**
   * Sección o subsección del menú de transparencia donde se publica (Resolución DIGEIG 002-2021).
   */
  seccionTransparencia?:
    | (
        | 'base-legal/constitucion'
        | 'base-legal/leyes'
        | 'base-legal/decretos'
        | 'base-legal/resoluciones'
        | 'base-legal/otras-normativas'
        | 'marco-legal/leyes'
        | 'marco-legal/decretos'
        | 'marco-legal/resoluciones'
        | 'marco-legal/otras-normativas'
        | 'estructura-organica'
        | 'oai/derechos'
        | 'oai/estructura'
        | 'oai/manual-organizacion'
        | 'oai/manual-procedimiento'
        | 'oai/estadisticas'
        | 'oai/rai'
        | 'oai/informacion-clasificada'
        | 'oai/indice-documentos'
        | 'oai/saip'
        | 'oai/indice-transparencia'
        | 'plan-estrategico/planificacion'
        | 'plan-estrategico/poa'
        | 'plan-estrategico/memorias'
        | 'publicaciones'
        | 'estadisticas'
        | 'servicios'
        | 'portal-311/enlace'
        | 'portal-311/estadisticas'
        | 'declaracion-jurada'
        | 'presupuesto/aprobado'
        | 'presupuesto/ejecucion'
        | 'recursos-humanos/nomina'
        | 'recursos-humanos/jubilaciones'
        | 'recursos-humanos/concursa'
        | 'programas-asistenciales'
        | 'compras/registro-proveedor'
        | 'compras/pacc'
        | 'compras/licitacion-publica'
        | 'compras/licitacion-restringida'
        | 'compras/sorteo-obras'
        | 'compras/comparaciones-precios'
        | 'compras/compras-menores'
        | 'compras/subasta-inversa'
        | 'compras/debajo-umbral'
        | 'compras/mipymes'
        | 'compras/casos-excepcion'
        | 'compras/estados-cuentas-suplidores'
        | 'proyectos'
        | 'finanzas/estados-financieros'
        | 'finanzas/informes-financieros'
        | 'finanzas/ingresos-egresos'
        | 'finanzas/auditorias'
        | 'finanzas/activos-fijos'
        | 'finanzas/inventario'
        | 'datos-abiertos'
        | 'cep/miembros'
        | 'cep/compromiso'
        | 'cep/plan-trabajo'
        | 'consulta-publica'
      )
    | null;
  /**
   * Año al que corresponde la información.
   */
  anio?: number | null;
  /**
   * Mes, trimestre o anual, si la publicación es periódica.
   */
  periodo?:
    | (
        | 'anual'
        | 't1'
        | 't2'
        | 't3'
        | 't4'
        | 'm01'
        | 'm02'
        | 'm03'
        | 'm04'
        | 'm05'
        | 'm06'
        | 'm07'
        | 'm08'
        | 'm09'
        | 'm10'
        | 'm11'
        | 'm12'
      )
    | null;
  /**
   * El Marco legal se presenta agrupado por tipo y ordenado por fecha (A2 4.02).
   */
  tipoNorma?: ('constitucion' | 'ley' | 'decreto' | 'resolucion' | 'reglamento' | 'normativa' | 'otra') | null;
  categoria?: (number | null) | Categoria;
  origen?: {
    url?: string | null;
    identificador?: string | null;
  };
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Complete los 15 campos de la ficha (NORTIC A5). Antes de producción, todos los servicios publicados deben tener la ficha completa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios".
 */
export interface Servicio {
  id: number;
  nombre: string;
  /**
   * Cómo lo reconoce la ciudadanía, cuando aplique.
   */
  nombreColoquial?: string | null;
  /**
   * Se genera del título si se deja vacío. Solo minúsculas, números y guiones.
   */
  slug: string;
  resumen: string;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Por ejemplo: arrendatarios de los complejos administrados por CORPHOTELS.
   */
  dirigidoA?: string | null;
  areaResponsable?: string | null;
  contactoArea?: {
    telefono?: string | null;
    extension?: string | null;
    correo?: string | null;
  };
  requisitos?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  procedimiento?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Días y horas en que se presta o atiende el servicio.
   */
  horario?: string | null;
  /**
   * Monto en RD$ y forma de pago, o «Gratuito».
   */
  costo?: string | null;
  /**
   * Plazo para responder la solicitud, cuando aplique (se muestra también en la confirmación).
   */
  tiempoRespuesta?: string | null;
  /**
   * Plazo para entregar el resultado del servicio.
   */
  tiempoRealizacion?: string | null;
  canales?: ('en-linea' | 'presencial' | 'telefono' | 'correo')[] | null;
  /**
   * Plataforma para la prestación del servicio, si existe.
   */
  acceso?: {
    solicitudEnLinea?: boolean | null;
    /**
     * Solo https://, por ejemplo una plataforma de servicios del Estado.
     */
    url?: string | null;
  };
  informacionAdicional?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo calcula el CMS al guardar.
   */
  fichaCompleta?: boolean | null;
  camposPendientes?: string | null;
  destacado?: boolean | null;
  listaParaRevision?: boolean | null;
  seo?: {
    /**
     * Si se deja vacío se usa el título. Máximo 70 caracteres.
     */
    titulo?: string | null;
    /**
     * Resumen propio de esta página. Máximo 160 caracteres.
     */
    descripcion?: string | null;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Lo que pasa en el carrusel grande de la portada. El avance automático se ajusta en Portada › Ajustes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diapositivas".
 */
export interface Diapositiva {
  id: number;
  /**
   * Si elige una noticia, se usan su foto, su título y su enlace; los campos de abajo son opcionales.
   */
  noticia?: (number | null) | Noticia;
  /**
   * Obligatorio si no elige una noticia.
   */
  titulo?: string | null;
  /**
   * Horizontal, al menos 1600 × 600 px. Obligatoria si no elige una noticia.
   */
  imagen?: (number | null) | Medio;
  /**
   * Ruta interna (/servicios) o enlace https:// de un portal del Estado.
   */
  enlace?: string | null;
  textoBoton?: string | null;
  desde?: string | null;
  hasta?: string | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  titulo: string;
  descripcion?: string | null;
  imagen: number | Medio;
  /**
   * Ruta interna (/servicios) o enlace https:// de un portal del Estado.
   */
  enlace?: string | null;
  textoEnlace?: string | null;
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preguntas-frecuentes".
 */
export interface PreguntasFrecuente {
  id: number;
  pregunta: string;
  respuesta: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  nombre: string;
  ubicacion: 'principal' | 'pie-informate';
  elementos?:
    | {
        etiqueta: string;
        /**
         * Interna (/sobre-nosotros/historia) o externa (https://...). Las externas abren en pestaña nueva.
         */
        url: string;
        hijos?:
          | {
              etiqueta: string;
              /**
               * Interna (/sobre-nosotros/historia) o externa (https://...). Las externas abren en pestaña nueva.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Texto que se muestra arriba de los documentos de una sección de transparencia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos-transparencia".
 */
export interface TextosTransparencia {
  id: number;
  seccion:
    | 'inicio'
    | 'base-legal'
    | 'marco-legal'
    | 'oai'
    | 'plan-estrategico'
    | 'portal-311'
    | 'presupuesto'
    | 'recursos-humanos'
    | 'compras'
    | 'finanzas'
    | 'cep'
    | 'base-legal/constitucion'
    | 'base-legal/leyes'
    | 'base-legal/decretos'
    | 'base-legal/resoluciones'
    | 'base-legal/otras-normativas'
    | 'marco-legal/leyes'
    | 'marco-legal/decretos'
    | 'marco-legal/resoluciones'
    | 'marco-legal/otras-normativas'
    | 'estructura-organica'
    | 'oai/derechos'
    | 'oai/estructura'
    | 'oai/manual-organizacion'
    | 'oai/manual-procedimiento'
    | 'oai/estadisticas'
    | 'oai/rai'
    | 'oai/informacion-clasificada'
    | 'oai/indice-documentos'
    | 'oai/saip'
    | 'oai/indice-transparencia'
    | 'plan-estrategico/planificacion'
    | 'plan-estrategico/poa'
    | 'plan-estrategico/memorias'
    | 'publicaciones'
    | 'estadisticas'
    | 'servicios'
    | 'portal-311/enlace'
    | 'portal-311/estadisticas'
    | 'declaracion-jurada'
    | 'presupuesto/aprobado'
    | 'presupuesto/ejecucion'
    | 'recursos-humanos/nomina'
    | 'recursos-humanos/jubilaciones'
    | 'recursos-humanos/concursa'
    | 'programas-asistenciales'
    | 'compras/registro-proveedor'
    | 'compras/pacc'
    | 'compras/licitacion-publica'
    | 'compras/licitacion-restringida'
    | 'compras/sorteo-obras'
    | 'compras/comparaciones-precios'
    | 'compras/compras-menores'
    | 'compras/subasta-inversa'
    | 'compras/debajo-umbral'
    | 'compras/mipymes'
    | 'compras/casos-excepcion'
    | 'compras/estados-cuentas-suplidores'
    | 'proyectos'
    | 'finanzas/estados-financieros'
    | 'finanzas/informes-financieros'
    | 'finanzas/ingresos-egresos'
    | 'finanzas/auditorias'
    | 'finanzas/activos-fijos'
    | 'finanzas/inventario'
    | 'datos-abiertos'
    | 'cep/miembros'
    | 'cep/compromiso'
    | 'cep/plan-trabajo'
    | 'consulta-publica';
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Contactos, sugerencias y solicitudes recibidos por el portal. Los datos personales están cifrados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos".
 */
export interface Caso {
  id: number;
  numero: string;
  tipo: 'contacto' | 'sugerencia' | 'solicitud';
  estado: 'recibido' | 'en-proceso' | 'respondido' | 'cerrado';
  servicio?: (number | null) | Servicio;
  asunto?: string | null;
  nombre?: string | null;
  correo?: string | null;
  telefono?: string | null;
  cedula?: string | null;
  mensaje?: string | null;
  consentimiento: {
    aceptado: boolean;
    fecha?: string | null;
    texto?: string | null;
  };
  notasInternas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "encuestas".
 */
export interface Encuesta {
  id: number;
  calificacion: number;
  facilidad?: ('si' | 'no') | null;
  comentario?: string | null;
  tipo?: string | null;
  servicio?: (number | null) | Servicio;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las cuentas y los roles se administran en Entra ID. Aquí solo se activa o desactiva el acceso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  email: string;
  /**
   * Asignados en Entra ID (roles de aplicación).
   */
  roles?: ('editor' | 'publicador' | 'oai' | 'administrador' | 'auditor')[] | null;
  activo?: boolean | null;
  entraOid?: string | null;
  ultimoAcceso?: string | null;
  sesionId?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'usuarios';
}
/**
 * Registro inalterable de accesos, permisos y publicaciones. Solo lectura.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora".
 */
export interface Bitacora {
  id: number;
  fecha: string;
  evento:
    | 'inicio_sesion'
    | 'inicio_sesion_rechazado'
    | 'cierre_sesion'
    | 'creacion'
    | 'modificacion'
    | 'publicacion'
    | 'despublicacion'
    | 'eliminacion'
    | 'cambio_permisos';
  usuarioId?: string | null;
  usuarioCorreo?: string | null;
  coleccion?: string | null;
  documentoId?: string | null;
  titulo?: string | null;
  ip?: string | null;
  detalle?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Direcciones del portal anterior que llevan a su equivalente en el portal nuevo (301).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirecciones".
 */
export interface Redireccione {
  id: number;
  origen: string;
  destino: string;
  tipo: 'exacta' | 'prefijo' | 'identificador';
  nota?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'paginas';
        value: number | Pagina;
      } | null)
    | ({
        relationTo: 'servicios';
        value: number | Servicio;
      } | null)
    | ({
        relationTo: 'diapositivas';
        value: number | Diapositiva;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'preguntas-frecuentes';
        value: number | PreguntasFrecuente;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'etiquetas';
        value: number | Etiqueta;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'textos-transparencia';
        value: number | TextosTransparencia;
      } | null)
    | ({
        relationTo: 'casos';
        value: number | Caso;
      } | null)
    | ({
        relationTo: 'encuestas';
        value: number | Encuesta;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'bitacora';
        value: number | Bitacora;
      } | null)
    | ({
        relationTo: 'redirecciones';
        value: number | Redireccione;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  fecha?: T;
  lugar?: T;
  imagen?: T;
  resumen?: T;
  contenido?: T;
  fuente?:
    | T
    | {
        nombre?: T;
        url?: T;
      };
  categorias?: T;
  etiquetas?: T;
  listaParaRevision?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        noIndexar?: T;
      };
  origen?:
    | T
    | {
        url?: T;
        identificador?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  padre?: T;
  imagen?: T;
  contenido?: T;
  documentos?: T;
  listaParaRevision?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios_select".
 */
export interface ServiciosSelect<T extends boolean = true> {
  nombre?: T;
  nombreColoquial?: T;
  slug?: T;
  resumen?: T;
  contenido?: T;
  dirigidoA?: T;
  areaResponsable?: T;
  contactoArea?:
    | T
    | {
        telefono?: T;
        extension?: T;
        correo?: T;
      };
  requisitos?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  procedimiento?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  horario?: T;
  costo?: T;
  tiempoRespuesta?: T;
  tiempoRealizacion?: T;
  canales?: T;
  acceso?:
    | T
    | {
        solicitudEnLinea?: T;
        url?: T;
      };
  informacionAdicional?: T;
  fichaCompleta?: T;
  camposPendientes?: T;
  destacado?: T;
  listaParaRevision?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diapositivas_select".
 */
export interface DiapositivasSelect<T extends boolean = true> {
  noticia?: T;
  titulo?: T;
  imagen?: T;
  enlace?: T;
  textoBoton?: T;
  desde?: T;
  hasta?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  imagen?: T;
  enlace?: T;
  textoEnlace?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preguntas-frecuentes_select".
 */
export interface PreguntasFrecuentesSelect<T extends boolean = true> {
  pregunta?: T;
  respuesta?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etiquetas_select".
 */
export interface EtiquetasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  nombre?: T;
  ubicacion?: T;
  elementos?:
    | T
    | {
        etiqueta?: T;
        url?: T;
        hijos?:
          | T
          | {
              etiqueta?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  origen?:
    | T
    | {
        url?: T;
        identificador?: T;
      };
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tarjeta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        completa?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  fechaCreacion?: T;
  area?: T;
  seccion?: T;
  seccionTransparencia?: T;
  anio?: T;
  periodo?: T;
  tipoNorma?: T;
  categoria?: T;
  origen?:
    | T
    | {
        url?: T;
        identificador?: T;
      };
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos-transparencia_select".
 */
export interface TextosTransparenciaSelect<T extends boolean = true> {
  seccion?: T;
  contenido?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos_select".
 */
export interface CasosSelect<T extends boolean = true> {
  numero?: T;
  tipo?: T;
  estado?: T;
  servicio?: T;
  asunto?: T;
  nombre?: T;
  correo?: T;
  telefono?: T;
  cedula?: T;
  mensaje?: T;
  consentimiento?:
    | T
    | {
        aceptado?: T;
        fecha?: T;
        texto?: T;
      };
  notasInternas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "encuestas_select".
 */
export interface EncuestasSelect<T extends boolean = true> {
  calificacion?: T;
  facilidad?: T;
  comentario?: T;
  tipo?: T;
  servicio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  roles?: T;
  activo?: T;
  entraOid?: T;
  ultimoAcceso?: T;
  sesionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora_select".
 */
export interface BitacoraSelect<T extends boolean = true> {
  fecha?: T;
  evento?: T;
  usuarioId?: T;
  usuarioCorreo?: T;
  coleccion?: T;
  documentoId?: T;
  titulo?: T;
  ip?: T;
  detalle?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirecciones_select".
 */
export interface RedireccionesSelect<T extends boolean = true> {
  origen?: T;
  destino?: T;
  tipo?: T;
  nota?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institucion".
 */
export interface Institucion {
  id: number;
  nombre: string;
  siglas: string;
  telefono: string;
  fax?: string | null;
  correo: string;
  direccion: string;
  apartadoPostal?: string | null;
  horario?: string | null;
  mapa: {
    latitud: number;
    longitud: number;
  };
  atencion: {
    tiempoContacto: string;
    tiempoSugerencias: string;
    /**
     * Por ejemplo, el horario de atención presencial.
     */
    otrasVias?: string | null;
  };
  /**
   * En móvil se muestran las 4 primeras (A2 3.04.c). Íconos oficiales, sin complementos.
   */
  redes?:
    | {
        red: 'facebook' | 'instagram' | 'x' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portada".
 */
export interface Portada {
  id: number;
  /**
   * Siempre con botón de pausa; se detiene al pasar el mouse o con el teclado.
   */
  avanceAutomatico?: boolean | null;
  segundos?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institucion_select".
 */
export interface InstitucionSelect<T extends boolean = true> {
  nombre?: T;
  siglas?: T;
  telefono?: T;
  fax?: T;
  correo?: T;
  direccion?: T;
  apartadoPostal?: T;
  horario?: T;
  mapa?:
    | T
    | {
        latitud?: T;
        longitud?: T;
      };
  atencion?:
    | T
    | {
        tiempoContacto?: T;
        tiempoSugerencias?: T;
        otrasVias?: T;
      };
  redes?:
    | T
    | {
        red?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portada_select".
 */
export interface PortadaSelect<T extends boolean = true> {
  avanceAutomatico?: T;
  segundos?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}